/*
 * FAASNewPage.java
 *
 * Created on June 25, 2011, 10:35 AM
 */

package etracs2.rpt.report.rptauction;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  arnel 
 */
public class NODInitialPage extends javax.swing.JPanel {
    
    /** Creates new form NODInitialPage */
    public NODInitialPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        xActionBar1 = new com.rameses.rcp.control.XActionBar();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle(" Initial Information");
        formPanel1.setBorder(xTitledBorder1);
        xLookupField1.setCaption("Property to process");
        xLookupField1.setCaptionWidth(120);
        xLookupField1.setExpression("#{tdno}");
        xLookupField1.setHandler("lookupledger");
        xLookupField1.setHint("Search RPT Ledger");
        xLookupField1.setName("ledger");
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 19));
        xLookupField1.setRequired(true);
        formPanel1.add(xLookupField1);

        xDateField1.setCaption("Bill Date");
        xDateField1.setCaptionWidth(120);
        xDateField1.setName("billdate");
        xDateField1.setPreferredSize(new java.awt.Dimension(100, 20));
        xDateField1.setRequired(true);
        formPanel1.add(xDateField1);

        xNumberField2.setCaption("Bill to Year");
        xNumberField2.setCaptionWidth(120);
        xNumberField2.setFieldType(Integer.class);
        xNumberField2.setName("billtoyear");
        xNumberField2.setPreferredSize(new java.awt.Dimension(50, 20));
        xNumberField2.setRequired(true);
        formPanel1.add(xNumberField2);

        jLabel2.setText("<html>Bill Date :<font color=\"red\">*</font></html>");
        formPanel1.add(jLabel2);

        jLabel3.setText("<html>Bill to Year :<font color=\"red\">*</font></html>");
        formPanel1.add(jLabel3);

        xActionBar1.setBorder(new com.rameses.rcp.control.border.XUnderlineBorder());
        xActionBar1.setName("formActions");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(xActionBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 346, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(xActionBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    // End of variables declaration//GEN-END:variables
    
}
