/*
 * ChangePinPage.java
 *
 * Created on August 6, 2012, 9:40 PM
 */

package etracs2.rpt.report.rptauction;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  PRMF
 */
@StyleSheet("etracs2/rpt/report/rptauction/RPTDelinquencyPage.style")
public class RPTDelinquencyPage extends javax.swing.JPanel {
    
    /** Creates new form ChangePinPage */
    public RPTDelinquencyPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xButton2 = new com.rameses.rcp.control.XButton();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        jLabel1 = new javax.swing.JLabel();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        jLabel2 = new javax.swing.JLabel();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xLabel1 = new com.rameses.rcp.control.XLabel();

        xButton2.setMnemonic('n');
        xButton2.setText("Next");
        xButton2.setCaption("Next");
        xButton2.setDefaultCommand(true);
        xButton2.setName("next");

        xPanel1.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("RPT Delinquency Criteria");
        xPanel1.setBorder(xTitledBorder1);
        jLabel1.setText("<html>Barangay :<font color=\"red\">*</font></html>");
        xPanel1.add(jLabel1);
        jLabel1.setBounds(20, 35, 110, 14);

        xComboBox2.setAllowNull(false);
        xComboBox2.setCaption("Barangay");
        xComboBox2.setCellPadding(new java.awt.Insets(10, 10, 0, 0));
        xComboBox2.setExpression("#{name}");
        xComboBox2.setItems("barangaylist");
        xComboBox2.setName("barangay");
        xComboBox2.setPreferredSize(new java.awt.Dimension(250, 22));
        xComboBox2.setRequired(true);
        xPanel1.add(xComboBox2);
        xComboBox2.setBounds(140, 30, 260, 22);

        jLabel2.setText("No of Delinquent Years :");
        xPanel1.add(jLabel2);
        jLabel2.setBounds(20, 58, 120, 14);

        xNumberField1.setFieldType(Integer.class);
        xNumberField1.setName("noofyears");
        xPanel1.add(xNumberField1);
        xNumberField1.setBounds(140, 55, 56, 20);

        xLabel1.setForeground(new java.awt.Color(153, 0, 0));
        xLabel1.setFont(new java.awt.Font("Arial", 1, 11));
        xLabel1.setName("msg");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, xPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(xLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 338, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(xButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(xPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(xButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(xLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XPanel xPanel1;
    // End of variables declaration//GEN-END:variables
    
}
