/*
 * AccountPage.java
 *
 * Created on February 27, 2011, 12:48 PM
 */

package etracs2.rpt.report.rptauction;

import com.rameses.rcp.ui.annotations.StyleSheet;

@StyleSheet("etracs2/rpt/report/rptauction/RPTDelinquenctyListPage.style")
public class RPTDelinquenctyListPage extends javax.swing.JPanel {
    
    /** Creates new form AccountPage */
    public RPTDelinquenctyListPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        jPanel1 = new javax.swing.JPanel();
        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xButton1 = new com.rameses.rcp.control.XButton();
        xButton2 = new com.rameses.rcp.control.XButton();
        xLabel1 = new com.rameses.rcp.control.XLabel();

        setLayout(new java.awt.BorderLayout());

        setPreferredSize(new java.awt.Dimension(748, 396));
        xActionBar1.setBorder(new com.rameses.rcp.control.border.XUnderlineBorder());
        xActionBar1.setName("formActions");
        add(xActionBar1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Listing");
        jPanel1.setBorder(xTitledBorder1);
        xDataTable1.setHandler("listHandler");
        xDataTable1.setName("selectedItem");
        jPanel1.add(xDataTable1, java.awt.BorderLayout.CENTER);

        formPanel1.setOrientation("HORIZONTAL");
        formPanel1.setPreferredSize(new java.awt.Dimension(500, 32));
        xButton1.setMnemonic('s');
        xButton1.setText("Select All");
        xButton1.setCaption("Select All");
        xButton1.setName("selectAll");
        xButton1.setPreferredSize(new java.awt.Dimension(80, 23));
        xButton1.setShowCaption(false);
        formPanel1.add(xButton1);

        xButton2.setMnemonic('d');
        xButton2.setText("Deselect All");
        xButton2.setCaption("Deselect All");
        xButton2.setName("deselectAll");
        xButton2.setPreferredSize(new java.awt.Dimension(100, 23));
        xButton2.setShowCaption(false);
        formPanel1.add(xButton2);

        xLabel1.setForeground(new java.awt.Color(153, 0, 0));
        xLabel1.setCellPadding(new java.awt.Insets(5, 0, 0, 0));
        xLabel1.setFont(new java.awt.Font("Arial", 1, 11));
        xLabel1.setName("msg");
        xLabel1.setPreferredSize(new java.awt.Dimension(500, 16));
        xLabel1.setShowCaption(false);
        formPanel1.add(xLabel1);

        jPanel1.add(formPanel1, java.awt.BorderLayout.SOUTH);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private javax.swing.JPanel jPanel1;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XLabel xLabel1;
    // End of variables declaration//GEN-END:variables
    
}
