
package etracs2.rpt.report.rptauction;

import com.rameses.rcp.ui.annotations.StyleSheet;

@StyleSheet("etracs2/rpt/report/rptauction/SettingsPage.style")
public class SettingsPage extends javax.swing.JPanel {
    
    /** Creates new form ListPage */
    public SettingsPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        xCheckBox1 = new com.rameses.rcp.control.XCheckBox();
        xCheckBox2 = new com.rameses.rcp.control.XCheckBox();
        xCheckBox3 = new com.rameses.rcp.control.XCheckBox();
        xCheckBox4 = new com.rameses.rcp.control.XCheckBox();
        xCheckBox5 = new com.rameses.rcp.control.XCheckBox();
        xCheckBox6 = new com.rameses.rcp.control.XCheckBox();
        xCheckBox7 = new com.rameses.rcp.control.XCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        xNumberField3 = new com.rameses.rcp.control.XNumberField();
        xNumberField4 = new com.rameses.rcp.control.XNumberField();
        xNumberField5 = new com.rameses.rcp.control.XNumberField();
        xNumberField6 = new com.rameses.rcp.control.XNumberField();
        xNumberField7 = new com.rameses.rcp.control.XNumberField();

        setLayout(new java.awt.BorderLayout());

        xActionBar1.setBorder(new com.rameses.rcp.control.border.XUnderlineBorder());
        xActionBar1.setDepends(new String[] {"selectedItem"});
        xActionBar1.setName("formActions");
        add(xActionBar1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("RPT Auction Settings");
        jPanel2.setBorder(xTitledBorder1);
        jPanel2.setOpaque(false);
        xCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox1.setText("Notice of Delinquency");
        xCheckBox1.setCheckValue(1);
        xCheckBox1.setEnabled(false);
        xCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox1.setName("entity.noticeofdelinquency");
        xCheckBox1.setOpaque(false);
        xCheckBox1.setUncheckValue(0);
        jPanel2.add(xCheckBox1);
        xCheckBox1.setBounds(40, 70, 260, 15);

        xCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox2.setText("Second Tracer");
        xCheckBox2.setCheckValue(1);
        xCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox2.setName("entity.secondtracer");
        xCheckBox2.setOpaque(false);
        xCheckBox2.setUncheckValue(0);
        jPanel2.add(xCheckBox2);
        xCheckBox2.setBounds(40, 90, 260, 15);

        xCheckBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox3.setText("Final Demand");
        xCheckBox3.setCheckValue(1);
        xCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox3.setName("entity.finaldemand");
        xCheckBox3.setOpaque(false);
        xCheckBox3.setUncheckValue(0);
        jPanel2.add(xCheckBox3);
        xCheckBox3.setBounds(40, 110, 260, 15);

        xCheckBox4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox4.setText("Warrant of Levy");
        xCheckBox4.setCheckValue(1);
        xCheckBox4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox4.setName("entity.warrantoflevy");
        xCheckBox4.setOpaque(false);
        xCheckBox4.setUncheckValue(0);
        jPanel2.add(xCheckBox4);
        xCheckBox4.setBounds(40, 130, 260, 15);

        xCheckBox5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox5.setText("Notice of Publication and Auction Sale");
        xCheckBox5.setCheckValue(1);
        xCheckBox5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox5.setName("entity.noticeofpublication");
        xCheckBox5.setOpaque(false);
        xCheckBox5.setUncheckValue(0);
        jPanel2.add(xCheckBox5);
        xCheckBox5.setBounds(40, 150, 260, 15);

        xCheckBox6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox6.setText("Certificate of Sale of Delinquent Real Property");
        xCheckBox6.setCheckValue(1);
        xCheckBox6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox6.setName("entity.certofsaleofproperty");
        xCheckBox6.setOpaque(false);
        xCheckBox6.setUncheckValue(0);
        jPanel2.add(xCheckBox6);
        xCheckBox6.setBounds(40, 170, 260, 15);

        xCheckBox7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox7.setText("Notice of Redemption");
        xCheckBox7.setCheckValue(1);
        xCheckBox7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox7.setName("entity.noticeofredemption");
        xCheckBox7.setOpaque(false);
        xCheckBox7.setUncheckValue(0);
        jPanel2.add(xCheckBox7);
        xCheckBox7.setBounds(40, 190, 260, 15);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText(" Check Available Demand Letters");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 50, 260, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("No of days expired");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(320, 50, 170, 14);

        xNumberField1.setCaption("No of Days Expired For Notice of Delinquency");
        xNumberField1.setDepends(new String[] {"entity.noticeofdelinquency"});
        xNumberField1.setFieldType(Integer.class);
        xNumberField1.setName("entity.noofdaysexpirednod");
        jPanel2.add(xNumberField1);
        xNumberField1.setBounds(320, 70, 80, 20);

        xNumberField2.setCaption("No of Days Expired for Secode Tracer");
        xNumberField2.setDepends(new String[] {"entity.secondtracer"});
        xNumberField2.setFieldType(Integer.class);
        xNumberField2.setName("entity.noofdaysexpiredst");
        jPanel2.add(xNumberField2);
        xNumberField2.setBounds(320, 90, 80, 20);

        xNumberField3.setCaption("No of Days Expired For Final Demand");
        xNumberField3.setDepends(new String[] {"entity.finaldemand"});
        xNumberField3.setFieldType(Integer.class);
        xNumberField3.setName("entity.noofdaysexpiredfd");
        jPanel2.add(xNumberField3);
        xNumberField3.setBounds(320, 110, 80, 20);

        xNumberField4.setCaption("No of Days Expired ForWarrant of Levy");
        xNumberField4.setDepends(new String[] {"entity.warrantoflevy"});
        xNumberField4.setFieldType(Integer.class);
        xNumberField4.setName("entity.noofdaysexpiredwol");
        jPanel2.add(xNumberField4);
        xNumberField4.setBounds(320, 130, 80, 20);

        xNumberField5.setCaption("No of Days Expired For Notice of Publication and Auction Sale");
        xNumberField5.setDepends(new String[] {"entity.noticeofpublication"});
        xNumberField5.setFieldType(Integer.class);
        xNumberField5.setName("entity.noofdaysexpirednopas");
        jPanel2.add(xNumberField5);
        xNumberField5.setBounds(320, 150, 80, 20);

        xNumberField6.setCaption("No of Days Expired For Certificate of Sale of Delinquent Real Property");
        xNumberField6.setDepends(new String[] {"entity.certofsaleofproperty"});
        xNumberField6.setFieldType(Integer.class);
        xNumberField6.setName("entity.noofdaysexpiredcsdrp");
        jPanel2.add(xNumberField6);
        xNumberField6.setBounds(320, 170, 80, 20);

        xNumberField7.setCaption("No of Days Expired For Certificate of Sale of Delinquent Real Property");
        xNumberField7.setDepends(new String[] {"entity.noticeofredemption"});
        xNumberField7.setFieldType(Integer.class);
        xNumberField7.setName("entity.noofdaysexpirednor");
        jPanel2.add(xNumberField7);
        xNumberField7.setBounds(320, 190, 80, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 540, 330);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XCheckBox xCheckBox1;
    private com.rameses.rcp.control.XCheckBox xCheckBox2;
    private com.rameses.rcp.control.XCheckBox xCheckBox3;
    private com.rameses.rcp.control.XCheckBox xCheckBox4;
    private com.rameses.rcp.control.XCheckBox xCheckBox5;
    private com.rameses.rcp.control.XCheckBox xCheckBox6;
    private com.rameses.rcp.control.XCheckBox xCheckBox7;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XNumberField xNumberField3;
    private com.rameses.rcp.control.XNumberField xNumberField4;
    private com.rameses.rcp.control.XNumberField xNumberField5;
    private com.rameses.rcp.control.XNumberField xNumberField6;
    private com.rameses.rcp.control.XNumberField xNumberField7;
    // End of variables declaration//GEN-END:variables
    
}
