/*
 * BPExpirySettingPage2.java
 *
 * Created on June 3, 2013, 3:54 PM
 */

package etracs2.bp.setting;

/**
 *
 * @author  rameses
 */
public class BPExpirySettingPage extends javax.swing.JPanel {
    
    /** Creates new form BPExpirySettingPage2 */
    public BPExpirySettingPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        jPanel1 = new javax.swing.JPanel();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        xDateField3 = new com.rameses.rcp.control.XDateField();
        xDateField4 = new com.rameses.rcp.control.XDateField();
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xDateField5 = new com.rameses.rcp.control.XDateField();

        setLayout(new java.awt.BorderLayout());

        xActionBar1.setName("formActions");
        add(xActionBar1, java.awt.BorderLayout.NORTH);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Surcharge Due Date");
        formPanel1.setBorder(xTitledBorder1);
        formPanel1.setPreferredSize(new java.awt.Dimension(166, 53));
        xDateField1.setCaption("Qtr 1");
        xDateField1.setCaptionWidth(45);
        xDateField1.setName("entity.surchargeqtr1.expirydate");
        xDateField1.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel1.add(xDateField1);

        xDateField2.setCaption("Qtr 2");
        xDateField2.setCaptionWidth(45);
        xDateField2.setName("entity.surchargeqtr2.expirydate");
        xDateField2.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel1.add(xDateField2);

        xDateField3.setCaption("Qtr 3");
        xDateField3.setCaptionWidth(45);
        xDateField3.setName("entity.surchargeqtr3.expirydate");
        xDateField3.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel1.add(xDateField3);

        xDateField4.setCaption("Qtr 4");
        xDateField4.setCaptionWidth(45);
        xDateField4.setName("entity.surchargeqtr4.expirydate");
        xDateField4.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel1.add(xDateField4);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("Discount Due Date");
        formPanel2.setBorder(xTitledBorder2);
        formPanel2.setPreferredSize(new java.awt.Dimension(166, 53));
        xDateField5.setCaption("Qtr 1");
        xDateField5.setCaptionWidth(45);
        xDateField5.setName("entity.discountqtr1.expirydate");
        xDateField5.setPreferredSize(new java.awt.Dimension(120, 19));
        formPanel2.add(xDateField5);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, formPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(formPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        add(jPanel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel2;
    private javax.swing.JPanel jPanel1;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XDateField xDateField3;
    private com.rameses.rcp.control.XDateField xDateField4;
    private com.rameses.rcp.control.XDateField xDateField5;
    // End of variables declaration//GEN-END:variables
    
}
