/*
 * AbstractOfCollectionInitPage.java
 *
 * Created on June 3, 2011, 1:35 PM
 */

package etracs2.rpt.report;

import com.rameses.rcp.ui.annotations.StyleSheet;

@StyleSheet
public class RPTBatchBillingReportPage extends javax.swing.JPanel {
    
    /**
     * Creates new form AbstractOfCollectionInitPage
     */
    public RPTBatchBillingReportPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xRadio1 = new com.rameses.rcp.control.XRadio();
        xComboBox5 = new com.rameses.rcp.control.XComboBox();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xRadio2 = new com.rameses.rcp.control.XRadio();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xLabel1 = new com.rameses.rcp.control.XLabel();

        setPreferredSize(new java.awt.Dimension(603, 291));
        xActionBar1.setBorder(new com.rameses.rcp.control.border.XUnderlineBorder());
        xActionBar1.setName("formActions");
        xActionBar1.setPadding(new java.awt.Insets(0, 5, 0, 0));

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Billing Options");
        formPanel1.setBorder(xTitledBorder1);
        formPanel1.setCaptionWidth(120);
        formPanel1.setPadding(new java.awt.Insets(5, 10, 5, 25));
        xRadio1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xRadio1.setText(" By Barangay");
        xRadio1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xRadio1.setName("batchoption");
        xRadio1.setOptionValue("bybarangay");
        xRadio1.setShowCaption(false);
        formPanel1.add(xRadio1);

        xComboBox5.setAllowNull(false);
        xComboBox5.setCaption("Municipality/District");
        xComboBox5.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xComboBox5.setDepends(new String[] {"batchoption"});
        xComboBox5.setExpression("#{lguname}");
        xComboBox5.setIndex(-100);
        xComboBox5.setItems("lgus");
        xComboBox5.setName("lgu");
        xComboBox5.setPreferredSize(new java.awt.Dimension(0, 21));
        formPanel1.add(xComboBox5);

        xComboBox1.setCaption("Barangay");
        xComboBox1.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xComboBox1.setDepends(new String[] {"batchoption"});
        xComboBox1.setDynamic(true);
        xComboBox1.setExpression("#{lguname}");
        xComboBox1.setItems("barangays");
        xComboBox1.setName("barangay");
        xComboBox1.setPreferredSize(new java.awt.Dimension(0, 21));
        formPanel1.add(xComboBox1);

        xRadio2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xRadio2.setText("By TD No");
        xRadio2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xRadio2.setName("batchoption");
        xRadio2.setOptionValue("bytd");
        xRadio2.setShowCaption(false);
        formPanel1.add(xRadio2);

        xTextField1.setCaption("From");
        xTextField1.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xTextField1.setDepends(new String[] {"batchoption"});
        xTextField1.setName("fromtdno");
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 20));
        formPanel1.add(xTextField1);

        xTextField2.setCaption("To");
        xTextField2.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xTextField2.setDepends(new String[] {"batchoption"});
        xTextField2.setName("totdno");
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 20));
        formPanel1.add(xTextField2);

        xLabel1.setForeground(new java.awt.Color(153, 0, 0));
        xLabel1.setFont(new java.awt.Font("Arial", 1, 11));
        xLabel1.setName("msg");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, xActionBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, xLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, formPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(xActionBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox5;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XRadio xRadio1;
    private com.rameses.rcp.control.XRadio xRadio2;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    // End of variables declaration//GEN-END:variables
    
}
