/*
 * BPReportInitPage.java
 *
 * Created on September 8, 2011, 1:31 PM
 */

package kapalog.bp.reports;

/**
 *
 * @author  jzamora
 */
public class BPReportInitPage extends javax.swing.JPanel {
    
    /** Creates new form BPReportInitPage */
    public BPReportInitPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xComboBox4 = new com.rameses.rcp.control.XComboBox();
        xComboBox5 = new com.rameses.rcp.control.XComboBox();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xActionBar1 = new com.rameses.rcp.control.XActionBar();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Initial Information");
        formPanel1.setBorder(xTitledBorder1);
        xNumberField1.setCaption("Year");
        xNumberField1.setCaptionWidth(100);
        xNumberField1.setCellPadding(new java.awt.Insets(10, 10, 0, 0));
        xNumberField1.setFieldType(Integer.class);
        xNumberField1.setName("year");
        xNumberField1.setPreferredSize(new java.awt.Dimension(100, 19));
        xNumberField1.setRequired(true);
        formPanel1.add(xNumberField1);

        xComboBox4.setCaption("Quarter");
        xComboBox4.setCaptionWidth(100);
        xComboBox4.setCellPadding(new java.awt.Insets(0, 10, 0, 0));
        xComboBox4.setItems("qtrlist");
        xComboBox4.setName("quarter");
        xComboBox4.setPreferredSize(new java.awt.Dimension(150, 22));
        formPanel1.add(xComboBox4);

        xComboBox5.setCaption("Month");
        xComboBox5.setCaptionWidth(100);
        xComboBox5.setCellPadding(new java.awt.Insets(0, 10, 0, 0));
        xComboBox5.setDepends(new String[] {"quarter"});
        xComboBox5.setDynamic(true);
        xComboBox5.setExpression("#{caption}");
        xComboBox5.setItems("monthlist");
        xComboBox5.setName("month");
        xComboBox5.setPreferredSize(new java.awt.Dimension(150, 22));
        formPanel1.add(xComboBox5);

        xComboBox3.setAllowNull(false);
        xComboBox3.setCaption("Status");
        xComboBox3.setCaptionWidth(100);
        xComboBox3.setCellPadding(new java.awt.Insets(0, 10, 0, 0));
        xComboBox3.setItems("statusList");
        xComboBox3.setName("status");
        xComboBox3.setPreferredSize(new java.awt.Dimension(150, 22));
        xComboBox3.setRequired(true);
        formPanel1.add(xComboBox3);

        xComboBox2.setCaption("Barangay");
        xComboBox2.setCaptionWidth(100);
        xComboBox2.setCellPadding(new java.awt.Insets(0, 10, 0, 0));
        xComboBox2.setExpression("#{barangayname}");
        xComboBox2.setItems("barangaylist");
        xComboBox2.setName("barangay");
        xComboBox2.setPreferredSize(new java.awt.Dimension(0, 22));
        formPanel1.add(xComboBox2);

        xActionBar1.setBorder(new com.rameses.rcp.control.border.XUnderlineBorder());
        xActionBar1.setName("formActions");
        xActionBar1.setPadding(new java.awt.Insets(0, 5, 0, 0));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(xActionBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 409, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(xActionBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(formPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 201, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XComboBox xComboBox4;
    private com.rameses.rcp.control.XComboBox xComboBox5;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    // End of variables declaration//GEN-END:variables
    
}
