/*
 * UnremittedCollectionSummaryPage.java
 *
 * Created on January 22, 2012, 9:32 AM
 */

package etracs2.tc.collection;

import com.rameses.rcp.ui.annotations.StyleSheet;
import java.math.BigDecimal;

/**
 *
 * @author  arnelretiza
 */
@StyleSheet("etracs2/tc/collection/UnremittedCollectionSummaryPage.style")
public class UnremittedCollectionSummaryPage extends javax.swing.JPanel {
    
    /** Creates new form BatchCaptureInitPage */
    public UnremittedCollectionSummaryPage() {
        initComponents();  
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        formPanel2 = new com.rameses.rcp.util.FormPanel();
        xNumberField1 = new com.rameses.rcp.control.XNumberField();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xRadio1 = new com.rameses.rcp.control.XRadio();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xRadio2 = new com.rameses.rcp.control.XRadio();
        formPanel5 = new com.rameses.rcp.util.FormPanel();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        formPanel4 = new com.rameses.rcp.util.FormPanel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xButton1 = new com.rameses.rcp.control.XButton();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Cash Tendered Info");
        formPanel2.setBorder(xTitledBorder1);
        formPanel2.setCaptionWidth(135);
        xNumberField1.setCaption("Cash Tendered");
        xNumberField1.setFieldType(BigDecimal.class);
        xNumberField1.setIndex(5);
        xNumberField1.setName("cashtendered");
        xNumberField1.setPreferredSize(new java.awt.Dimension(200, 20));
        formPanel2.add(xNumberField1);

        xLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel4.setCaption("Change");
        xLabel4.setName("entity.change");
        xLabel4.setPreferredSize(new java.awt.Dimension(200, 20));
        formPanel2.add(xLabel4);

        xPanel1.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setTitle("Collection Information");
        xPanel1.setBorder(xTitledBorder2);
        xRadio1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xRadio1.setText("By Series No");
        xRadio1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xRadio1.setName("entity.type");
        xRadio1.setOptionValue("byseries");
        xPanel1.add(xRadio1);
        xRadio1.setBounds(10, 30, 270, 15);

        formPanel1.setCaptionPadding(new java.awt.Insets(0, 0, 0, 5));
        formPanel1.setCaptionWidth(100);
        formPanel1.setPadding(new java.awt.Insets(0, 0, 5, 5));
        xComboBox2.setCaption("AF Control");
        xComboBox2.setDepends(new String[] {"entity.type"});
        xComboBox2.setDynamic(true);
        xComboBox2.setExpression("#{afid}");
        xComboBox2.setImmediate(true);
        xComboBox2.setIndex(1);
        xComboBox2.setItems("afcontrollist");
        xComboBox2.setName("entity.afcontrol");
        xComboBox2.setPreferredSize(new java.awt.Dimension(200, 22));
        formPanel1.add(xComboBox2);

        xTextField1.setCaption("From Series");
        xTextField1.setDepends(new String[] {"entity.type"});
        xTextField1.setIndex(2);
        xTextField1.setName("entity.fromseries");
        xTextField1.setPreferredSize(new java.awt.Dimension(200, 20));
        formPanel1.add(xTextField1);

        xTextField2.setCaption("To Series");
        xTextField2.setDepends(new String[] {"entity.type"});
        xTextField2.setIndex(3);
        xTextField2.setName("entity.toseries");
        xTextField2.setPreferredSize(new java.awt.Dimension(200, 20));
        formPanel1.add(xTextField2);

        xPanel1.add(formPanel1);
        formPanel1.setBounds(40, 50, 320, 70);

        xRadio2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xRadio2.setText("By Payor Name");
        xRadio2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xRadio2.setName("entity.type");
        xRadio2.setOptionValue("bytaxpayer");
        xPanel1.add(xRadio2);
        xRadio2.setBounds(10, 130, 270, 15);

        formPanel5.setCaptionWidth(100);
        formPanel5.setPadding(new java.awt.Insets(0, 0, 5, 5));
        xTextField3.setCaption("Payor Name");
        xTextField3.setDepends(new String[] {"entity.type"});
        xTextField3.setName("entity.payorname");
        xTextField3.setPreferredSize(new java.awt.Dimension(200, 20));
        formPanel5.add(xTextField3);

        xPanel1.add(formPanel5);
        formPanel5.setBounds(40, 150, 310, 25);

        formPanel4.setCaptionWidth(115);
        formPanel4.setPadding(new java.awt.Insets(5, 5, 5, 0));
        xLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel5.setCaption("Cash");
        xLabel5.setName("entity.cash");
        xLabel5.setPreferredSize(new java.awt.Dimension(200, 20));
        formPanel4.add(xLabel5);

        xLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel6.setCaption("Check");
        xLabel6.setName("entity.otherpayment");
        xLabel6.setPreferredSize(new java.awt.Dimension(200, 20));
        formPanel4.add(xLabel6);

        xLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        xLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel7.setCaption("Total Amount");
        xLabel7.setName("entity.totalamount");
        xLabel7.setPreferredSize(new java.awt.Dimension(200, 20));
        formPanel4.add(xLabel7);

        xPanel1.add(formPanel4);
        formPanel4.setBounds(20, 180, 320, 80);

        xButton1.setText("Compute");
        xButton1.setName("compute");
        xPanel1.add(xButton1);
        xButton1.setBounds(247, 260, 90, 23);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, formPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, xPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(xPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 298, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(formPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private com.rameses.rcp.util.FormPanel formPanel2;
    private com.rameses.rcp.util.FormPanel formPanel4;
    private com.rameses.rcp.util.FormPanel formPanel5;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel5;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XNumberField xNumberField1;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XRadio xRadio1;
    private com.rameses.rcp.control.XRadio xRadio2;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    // End of variables declaration//GEN-END:variables
    
}
