/*
 * ChangePinPage.java
 *
 * Created on August 6, 2012, 9:40 PM
 */

package etracs2.rpt.report.rptdelinquency;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author  PRMF
 */
@StyleSheet("etracs2/rpt/report/rptdelinquency/RPTDelinquencyPage.style")
public class RPTDelinquencyPage extends javax.swing.JPanel {
    
    /** Creates new form ChangePinPage */
    public RPTDelinquencyPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xButton2 = new com.rameses.rcp.control.XButton();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xNumberField2 = new com.rameses.rcp.control.XNumberField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xCheckBox1 = new com.rameses.rcp.control.XCheckBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        xLabel1 = new com.rameses.rcp.control.XLabel();

        xButton2.setMnemonic('n');
        xButton2.setText("Next");
        xButton2.setCaption("Next");
        xButton2.setDefaultCommand(true);
        xButton2.setName("next");

        xPanel1.setLayout(null);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("RPT Delinquency Criteria");
        xPanel1.setBorder(xTitledBorder1);
        xComboBox1.setCaption("Filter By");
        xComboBox1.setDynamic(true);
        xComboBox1.setExpression("#{caption}");
        xComboBox1.setImmediate(true);
        xComboBox1.setItems("filterlist");
        xComboBox1.setName("filter");
        xComboBox1.setPreferredSize(new java.awt.Dimension(150, 22));
        xPanel1.add(xComboBox1);
        xComboBox1.setBounds(90, 55, 180, 22);

        xNumberField2.setCaption("Value");
        xNumberField2.setDepends(new String[] {"filter"});
        xNumberField2.setFieldType(Integer.class);
        xNumberField2.setName("entity.value");
        xNumberField2.setPreferredSize(new java.awt.Dimension(80, 22));
        xPanel1.add(xNumberField2);
        xNumberField2.setBounds(90, 80, 180, 22);

        jLabel1.setText("<html>Barangay :<font color=\"red\">*</font></html>");
        xPanel1.add(jLabel1);
        jLabel1.setBounds(20, 35, 110, 14);

        jLabel2.setText("Value :");
        xPanel1.add(jLabel2);
        jLabel2.setBounds(20, 85, 100, 14);

        xDateField1.setCaption("Advance Billing Date");
        xDateField1.setCaptionWidth(120);
        xDateField1.setCellPadding(new java.awt.Insets(0, 90, 0, 0));
        xDateField1.setDepends(new String[] {"entity.advancepayment"});
        xDateField1.setName("entity.billdate");
        xDateField1.setPreferredSize(new java.awt.Dimension(100, 19));
        xPanel1.add(xDateField1);
        xDateField1.setBounds(160, 135, 160, 19);

        xCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xCheckBox1.setText("Is Advance?");
        xCheckBox1.setCaption("");
        xCheckBox1.setCaptionWidth(90);
        xCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox1.setName("entity.advancepayment");
        xCheckBox1.setOpaque(false);
        xPanel1.add(xCheckBox1);
        xCheckBox1.setBounds(90, 120, 110, 15);

        xComboBox2.setAllowNull(false);
        xComboBox2.setCaption("Barangay");
        xComboBox2.setCellPadding(new java.awt.Insets(10, 10, 0, 0));
        xComboBox2.setExpression("#{name}");
        xComboBox2.setItems("barangaylist");
        xComboBox2.setName("barangay");
        xComboBox2.setPreferredSize(new java.awt.Dimension(250, 22));
        xComboBox2.setRequired(true);
        xPanel1.add(xComboBox2);
        xComboBox2.setBounds(90, 30, 260, 22);

        jLabel3.setText("Filter By :");
        xPanel1.add(jLabel3);
        jLabel3.setBounds(20, 60, 90, 14);

        jLabel4.setText("Billing Date :");
        xPanel1.add(jLabel4);
        jLabel4.setBounds(90, 140, 80, 14);

        xLabel1.setForeground(new java.awt.Color(153, 0, 0));
        xLabel1.setFont(new java.awt.Font("Arial", 1, 11));
        xLabel1.setName("msg");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(xPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 421, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(xLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(xButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(xPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 199, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(xLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(xButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XCheckBox xCheckBox1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XNumberField xNumberField2;
    private com.rameses.rcp.control.XPanel xPanel1;
    // End of variables declaration//GEN-END:variables
    
}
